#! /bin/bash

# this script will give these features for each file
# 1. you know or like occur as a verbal disfluency
# 2. there is a restatement in an utterance

# first get everything in brackets
raw_file=$1
grep '^counselor\.' $raw_file | cut -f2 |  sed 's/( um )/ um /g;s/( uh )/ uh /g;s/( eh )/ eh /g;s/( ah )/ ah /g'  | sed 's/^/~~/g;s/$/~~/g' | sed 's/~~[^),^(]*~~//g' |  sed 's/^[^(]*(//g;s/)[^(]*(//g;s/)[^(]*$//g' > $raw_file'.all_dis'

sed 's/ you know /~~/g' $raw_file'.all_dis' | sed 's/[^~]*//g' | sed 's/~[~]*/yk/g' >$raw_file'.yk' # for you know

sed 's/ like /~~/g' $raw_file'.all_dis' | sed 's/[^~]*//g' | sed 's/~[~]*/lk/g' >$raw_file'.lk' # for like

sed 's/\*/~~/g' $raw_file'.all_dis' | sed 's/[^~]*//g' | sed 's/~[~]*/inc/g' >$raw_file'.inc' # for incomplete words

sed 's/ like //g;s/ you know //g' $raw_file'.all_dis' | sed 's/[^\ ][^\ ]*/~/g' | sed 's/ //g' | sed 's/~[~]*/vr/g' >$raw_file'.verbal_restate'

paste -d' ' <(paste -d' ' $raw_file'.yk' $raw_file'.lk') <(paste -d' ' $raw_file'.inc' $raw_file'.verbal_restate') | sed 's/  / /g;s/^ //g;s/ $//g' | sed 's/  / /g;s/^ //g;s/ $//g' | tr 'a-z' 'A-Z'| sed 's/INC VR/INC/g' > $raw_file'.verbal_dis'



